### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by GhostEsso** [JoyTaribagshaw/JavaScript-Group-Capstone#31]
Hi **@riskmaris**,
Good job so far :+1: , I noticed that in your popup, you have split the different information about a movie into blocks. I have a suggestion, wouldn't it be better to put all this information in a single block, it will allow you more space on your popup which will reduce the scroll. Once again, congratulations to you and your partner for the job done.
Happy Coding :clap:

**Comment by faisalakb** [comment]
Good Job done so far.
